<?php if ($posts = $block->getPosts()): ?>
    <table border="1" cellspacing="0" cellpadding="10">
        <thead>
            <tr>
                <th>ID</th>
                <th>User ID</th>
                <th>Title</th>
                <th>Body</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($posts as $post): ?>
                <tr>
                    <td><?php echo $post->getId(); ?></td>
                    <td><?php echo $post->getUserId(); ?></td>
                    <td><?php echo $post->getTitle(); ?></td>
                    <td><?php echo $post->getBody(); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No posts found.</p>
<?php endif; ?>
